language: c

env:
  matrix:
    - VALAC=valac-0.24

before_install:
  - sudo pip install cpp-coveralls
install:
  - if [ "$VALAC" = "valac-0.24" ]; then
      sudo add-apt-repository -y ppa:vala-team &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq autotools-dev gnome-common gobject-introspection intltool libgee-0.8-dev libgirepository1.0-dev libjson-glib-dev "$VALAC";
    fi

script:
  ./autogen.sh --enable-code-coverage && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
